Pizzas/urls.py
from django.urls import path

from . import views

app_name= 'Pizzas'


urlpatterns=[
    path('', views.index,name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),

    
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Pizzas.urls')),
]

Pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pizza_name
    
class Topping(models.Model):
    pizza= models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name=models.CharField(max_length=200)
    date_added= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topping_name

Pizzas/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def index(request):
    return render(request, 'Pizzas/index.html')


def pizzas(request):
    pizzas= Pizza.objects.all()

    context= {'all_pizzas':pizzas}
    return render(request, 'Pizzas/pizzas.html', context)

def pizza(request,pizza_id):
    pizza= Pizza.objects.get(id=pizza_id)

    toppings=Topping.objects.filter(pizza=pizza).order_by('-date_added')

    context= {'pizza':pizza, 'toppings':toppings}
    return render(request, 'Pizzas/pizza.html', context)

Pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'Pizzas:index' %}">Pizzas</a>
    <a href="{% url 'Pizzas:pizzas' %}">pizzas</a>
</p>
</p>

{% block content %}

{% endblock content %}

Pizzas/templates/pizzas/index.html
{% extends "Pizzas/base.html" %}

{% block content %}
<p> 
    Here we have a list of pizzas that we want to teach
    you about. Enjoy!
</p>

{% endblock content %}

Pizzas/templates/pizzas/pizza.html
{% extends "Pizzas/base.html" %}

{% block content %}
<p> Pizzas</p>

<ul>
    {% for topping in toppings %}

    <li> 
        <p>{{topping.toppings_name}}</p>
        <p> {{topping.date_added}}</p>
    </li>
    {% empty %}
    <li> No toppings have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

Pizzas/templates/pizzas/pizzas.html
{% extends "Pizzas/base.html" %}

{% block content %}
<p> Pizzas</p>

<ul>
    {% for pizza in all_pizzas %}

    <li>
         <a href="{% url 'Pizzas:pizza' pizza.id %}" >{{pizza}}</a>
    </li>
    {% empty %}
    <li> No pizzas have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}